"""empty message

Revision ID: 17a1e3fef273
Revises: 437ab24d1952
Create Date: 2020-09-30 11:17:18.002293

"""

# revision identifiers, used by Alembic.
revision = '17a1e3fef273'
down_revision = '437ab24d1952'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
